### ISSUE TITLE
Add a README 

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Revenant#1]
Add a small README to the repo. 

It should also contain some setup instructions, so that others can set this up on their own.

**Comment by Bhargav-Rao** [comment]
@thesecretmaster can you look into this when you're free? We're planning to host it somewhere, and need the setup instructions.

**Comment by thesecretmaster** [comment]
Ah yep, sorry, I just forgot about it.

**Comment by thesecretmaster** [comment]
Basic outline, until I write something out fully:

Run bundle install.
Currently hardcoded to post in room 167908, and only pull SO tags
Gets tags from https://raw.githubusercontent.com/SOBotics/Tagdor/master/SplitTags.csv
Prints all burninated tags that have risen again
You need a settings.yml file with:
```yaml
chatx_username:
chatx_password:
api_key:
```
